### ISSUE TITLE
Error : The function is not implemented.

### ISSUE THREAD

**Issue by xiechuanyu** [SensorsINI/ddd20-utils#2]
When I use the `export_ddd20_hdf.py` to export DDD17 data.
An error occurs.
> Traceback (most recent call last):
  File "ddd20-utils/export_ddd20_hdf.py", line 657, in <module>
    c = Controller(fname,)
  File "ddd20-utils/export_ddd20_hdf.py", line 542, in __init__
    cv2.namedWindow('control')
cv2.error: OpenCV(4.2.0) /io/opencv/modules/highgui/src/window.cpp:634: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

Enviroments:

> Ubuntu
Python2.7

**Comment by xiechuanyu** [comment]
I have use `export_ddd20_hdf.py` to export the dvs data from DDD17. Is that OK ?

**Comment by xiechuanyu** [comment]
Actually I want to export the raw dvs event data. So I try to use `export_ddd20_hdf.py`, sincce `export.py` only bin the event into frame-based representation.

**Comment by xiechuanyu** [comment]
Or can you tell me what`s the data format in `dvs` ?
I have used `h5py` to explore the original data `rec1487339175.hdf5`.
![image](https://user-images.githubusercontent.com/12131262/88127200-b6ae4b00-cc05-11ea-94fc-dda1bb51ae0d.png)

Once I thought the data was stored in a format shown in the below picture.
![image](https://user-images.githubusercontent.com/12131262/88127459-3cca9180-cc06-11ea-94aa-6e0ea172303c.png)

But I found that each grid contains an array, not a number. As shown below, Why ?  What does this mean ? How to understand the dvs data ?
![image](https://user-images.githubusercontent.com/12131262/88127490-553aac00-cc06-11ea-9857-6eb25b46b2e7.png)

**Comment by xiechuanyu** [comment]
我只是想导出 event data  怎么就这么难，或者你说明一下原始数据里 dvs 的 data 是啥意思？

**Comment by xiechuanyu** [comment]
I have found this error at [https://github.com/skvark/opencv-python/issues/323](https://github.com/skvark/opencv-python/issues/323).
> opencv-python-headless does not include GUI support (as explained by berak in the linked issue). Please read the README file and do as it suggests: uninstall opencv-python-headless and install opencv-python and you will get support for ....

**Comment by duguyue100** [comment]
Ok. So this tool as developed three years ago and at the time, the person who created it decided to save the data into a custom data type which basically violates the homogenous principle of HDF5. It took me a lot of time to figure out the decoding.
I will not encourage you to understand this encoding and it's not worth your time.

As in the exporting script, it's an ad-hoc script I modified from the `view.py` so that the data is reformatted into homogenous data arrays. In each exported HDF5, there are three datasets:

```
frame: [N, 260, 346], uint8
frame_ts: [N, 1], float32
event: [N, 4] , uint32
```

I'm investigating why the exported data for you is empty. I will post my findings later.

**Comment by xiechuanyu** [comment]
Thanks for your reply.  Does the `export_ddd20_hdf.py` only work on Linux ? Because the `cvNamedWindow` error only occurs on Windows.

**Comment by duguyue100** [comment]
I haven't used a Windows machine for years, I guess it won't work on Windows because of some ugly compatible issues.

I see that there are some errors related to GUI rendering for a Windows machine. I encourage you to try different opencv versions, maybe this error will disappear for certain versions.

By the way, I've fixed some changes in the lower APIs that somehow still use Python3 `queue`, you should pull the latest commit .

**Comment by duguyue100** [comment]
I've tried to export data from my machine with Ubuntu 16.04 + Python2.7 + OpenCV 3.3.1-dev (supplied with ROS).

I think it should not be very sensitive to the OpenCV version, generally, any version around OpenCV 4.0 should be fine.

**Comment by xiechuanyu** [comment]
Thanks very much for your help!
After I uninstall `opencv-python-headless`, and instead install `opencv-python`, I can export the data correctly.
